<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'montserrat-black' => array(
    'normal' => $rootDir . '/lib/fonts/Montserrat-Black',
    'bold' => $rootDir . '/lib/fonts/Montserrat-Black',
    'italic' => $rootDir . '/lib/fonts/Montserrat-Black',
    'bold_italic' => $rootDir . '/lib/fonts/Montserrat-Black',
  ),
  'montserrat_bold' => array(
    'normal' => $rootDir . '/lib/fonts/Montserrat_Bold',
    'bold' => $rootDir . '/lib/fonts/Montserrat_Bold',
    'italic' => $rootDir . '/lib/fonts/Montserrat_Bold',
    'bold_italic' => $rootDir . '/lib/fonts/Montserrat_Bold',
  ),
  'montserrat' => array(
    'normal' => $fontDir . '/montserrat-normal_97518ad8ea22a7bfe0a0f34ccf179c87',
    'black' => $fontDir . '/Montserrat-Black',
    'black_italic' => $fontDir . '/Montserrat-BlackItalic',
    'bold' => $fontDir . '/Montserrat-Bold',
    'bold_italic' => $fontDir . '/Montserrat-BoldItalic',
    'extra_bold' => $fontDir . '/Montserrat-ExtraBold',
    'extra_bold_italic' => $fontDir . '/Montserrat-ExtraBoldItalic',
    'extra_light' => $fontDir . '/Montserrat-ExtraLight',
    'extra_light_italic' => $fontDir . '/Montserrat-ExtraLightItalic',
    'italic' => $fontDir . '/Montserrat-Italic',
    'light' => $fontDir . '/Montserrat-Light',
    'light_italic' => $fontDir . '/Montserrat-LightItalic',
    'medium' => $fontDir . '/Montserrat-Medium',
    'medium_italic' => $fontDir . '/Montserrat-MediumItalic',
    'semi_bold' => $fontDir . '/Montserrat-SemiBold',
    'semi_bold_italic' => $fontDir . '/Montserrat-SemiBoldItalic',
    'thin' => $fontDir . '/Montserrat-Thin',
    'thin_italic' => $fontDir . '/Montserrat-ThinItalic',
  ),
  'montserrat-extrabold' => array(
    'normal' => $fontDir . '/montserrat-extrabold-normal_59cb9ff716963d20180698f5665b7511',
  ),
) ?>